KEY_WORDS = {
    'Nil': 'Logical symbol',
    'nil': 'Logical symbol',
    'NIL': 'Logical symbol',
    'T': 'Logical symbol',
    't': 'Logical symbol',
    # 'DEFINE': 'Keyword',
    # 'define': 'Keyword',
    'DEFUN': 'Keyword',
    'defun': 'Keyword',
    'DEFVAR': 'Keyword',
    'defvar': 'Keyword',
    'SETQ': 'Keyword',
    'setq': 'Keyword',
    'LIST': 'Keyword',
    'list': 'Keyword',
    'IF': 'Keyword',
    'if': 'Keyword',
    'COND': 'Keyword',
    'cond': 'Keyword',
    'LAMBDA': 'Keyword',
    'lambda': 'Keyword',
    'PRINT': 'Keyword',
    'print': 'Keyword',
    'car': 'Keyword',
    'CAR': 'Keyword',
    'cdr': 'Keyword',
    'CDR': 'Keyword',
    'empty': 'Keyword',
    'EMPTY': 'Keyword',
}

OPERATORS = {
    '+': 'Arithmetic operator',
    '-': 'Arithmetic operator',
    '*': 'Arithmetic operator',
    '/': 'Arithmetic operator',
    'mod': 'Arithmetic function',
    'incf': 'Arithmetic function',
    'decf': 'Arithmetic function',
    'string=': 'String operator',
    'string/=': 'String operator',
    'string>': 'String operator',
    'string<': 'String operator',
    'string>=': 'String operator',
    'string<=': 'String operator',
}