KEY_WORDS = {
    'Nil': 'Logical symbol',
    'nil': 'Logical symbol',
    'NIL': 'Logical symbol',
    'T': 'Logical symbol',
    't': 'Logical symbol',
    'DEFUN': 'Keyword',
    'defun': 'Keyword',
    'DEFVAR': 'Keyword',
    'defvar': 'Keyword',
    'SETQ': 'Keyword',
    'setq': 'Keyword',
    'LIST': 'Keyword',
    'list': 'Keyword',
    'IF': 'Keyword',
    'if': 'Keyword',
    'PRINT': 'Keyword',
    'print': 'Keyword',
    'car': 'Keyword',
    'CAR': 'Keyword',
    'cdr': 'Keyword',
    'CDR': 'Keyword',
    'empty': 'Keyword',
    'EMPTY': 'Keyword',
    'length': 'Keyword',
    'LENGTH': 'Keyword',
    'push': 'Keyword',
    'PUSH': 'Keyword',
    'progn': 'Keyword',
    'PROGN': 'Keyword',
    'truncate': 'Keyword',
    'TRUNCATE': 'Keyword',
    'load': 'KW',
    'LOAD': 'KW',
}

OPERATORS = {
    '+': 'Arithmetic operator',
    '-': 'Arithmetic operator',
    '*': 'Arithmetic operator',
    '/': 'Arithmetic operator',
    'mod': 'Arithmetic function',
    '>': 'Arithmetic operator',
    '<': 'Arithmetic operator',
    '=': 'Arithmetic operator',
    'string=': 'String operator',
    'string/=': 'String operator',
    'string>': 'String operator',
    'string<': 'String operator',
    'string>=': 'String operator',
    'string<=': 'String operator',
}